// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: first_service.proto

package first_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FirstServiceClient is the client API for FirstService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirstServiceClient interface {
	InsertPosts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InsertPostsResponse, error)
	CheckPosts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CheckPostsResponse, error)
}

type firstServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFirstServiceClient(cc grpc.ClientConnInterface) FirstServiceClient {
	return &firstServiceClient{cc}
}

func (c *firstServiceClient) InsertPosts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InsertPostsResponse, error) {
	out := new(InsertPostsResponse)
	err := c.cc.Invoke(ctx, "/service.FirstService/InsertPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firstServiceClient) CheckPosts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CheckPostsResponse, error) {
	out := new(CheckPostsResponse)
	err := c.cc.Invoke(ctx, "/service.FirstService/CheckPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstServiceServer is the server API for FirstService service.
// All implementations must embed UnimplementedFirstServiceServer
// for forward compatibility
type FirstServiceServer interface {
	InsertPosts(context.Context, *emptypb.Empty) (*InsertPostsResponse, error)
	CheckPosts(context.Context, *emptypb.Empty) (*CheckPostsResponse, error)
	mustEmbedUnimplementedFirstServiceServer()
}

// UnimplementedFirstServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFirstServiceServer struct {
}

func (UnimplementedFirstServiceServer) InsertPosts(context.Context, *emptypb.Empty) (*InsertPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertPosts not implemented")
}
func (UnimplementedFirstServiceServer) CheckPosts(context.Context, *emptypb.Empty) (*CheckPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPosts not implemented")
}
func (UnimplementedFirstServiceServer) mustEmbedUnimplementedFirstServiceServer() {}

// UnsafeFirstServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirstServiceServer will
// result in compilation errors.
type UnsafeFirstServiceServer interface {
	mustEmbedUnimplementedFirstServiceServer()
}

func RegisterFirstServiceServer(s grpc.ServiceRegistrar, srv FirstServiceServer) {
	s.RegisterService(&FirstService_ServiceDesc, srv)
}

func _FirstService_InsertPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstServiceServer).InsertPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.FirstService/InsertPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstServiceServer).InsertPosts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirstService_CheckPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstServiceServer).CheckPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.FirstService/CheckPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstServiceServer).CheckPosts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FirstService_ServiceDesc is the grpc.ServiceDesc for FirstService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirstService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.FirstService",
	HandlerType: (*FirstServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertPosts",
			Handler:    _FirstService_InsertPosts_Handler,
		},
		{
			MethodName: "CheckPosts",
			Handler:    _FirstService_CheckPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "first_service.proto",
}
